export const CHANGE_NAME = "CHANGE_NAME";
export const CHANGE_ADDRESS = "CHANGE_ADDRESS";

export const ADD_ACTIVITY = "ADD_ACTIVITY";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";
export const SET_ACTIVE_ACTIVITY = "SET_ACTIVE_ACTIVITY";
export const UPDATE_ACTIVITY = "UPDATE_ACTIVITY";

export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const SET_ACTIVE_TASK = "SET_ACTIVE_TASK";

export const ADD_PHASE = "ADD_PHASE";
export const UPDATE_PHASES = "UPDATE_PHASES";

export const ADD_PROJECT = "ADD_PROJECT";
export const UPDATE_PROJECTS = "UPDATE_PROJECTS";

export const SWITCH_COLORMODE = "SWITCH_COLORMODE";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
